import { Link } from "react-router-dom";
import ArrowForwardOutlinedIcon from "@mui/icons-material/ArrowForwardOutlined";
import PublicOutlinedIcon from "@mui/icons-material/PublicOutlined";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";
import HubOutlinedIcon from "@mui/icons-material/HubOutlined";
import RocketLaunchOutlinedIcon from "@mui/icons-material/RocketLaunchOutlined";
import AutoAwesomeOutlinedIcon from "@mui/icons-material/AutoAwesomeOutlined";
import HelpOutlineOutlinedIcon from "@mui/icons-material/HelpOutlineOutlined";
import ShieldOutlinedIcon from "@mui/icons-material/ShieldOutlined";
import FeedbackOutlinedIcon from "@mui/icons-material/FeedbackOutlined";
import ServiceArt from "../../components/ServiceArt";
import { serviceCatalog } from "../../content/serviceCatalog";

const why = [[PublicOutlinedIcon,"Access anywhere","Access multiple digital services from anywhere you are."],[LockOutlinedIcon,"Simple access","One account for your everyday needs."],[HubOutlinedIcon,"Connect everyone","People, businesses, and opportunities connected together."],[RocketLaunchOutlinedIcon,"Built for the future","A growing ecosystem designed for everyday life."]] as const;
const support = [[HelpOutlineOutlinedIcon,"Help Center","Find guides and answers.",["FAQs","Guides","Common questions"],"/help"],[ShieldOutlinedIcon,"Safety Center","Use SMAJ PI HUB with confidence.",["Privacy","Account safety","Reports","Protection"],"/help"],[FeedbackOutlinedIcon,"Feedback","Help improve SMAJ PI HUB.",["Send ideas","Report issues","Share experience"],"/contact"]] as const;

const DashboardPage = () => <main className="private-home"><section className="ecosystem-hero"><div><p className="private-kicker">SMAJ PI HUB</p><h1>Everything you need.<br />One place.</h1><p>Discover services built for everyday life.</p><Link className="private-primary-button" to="/app/services">Explore Services <ArrowForwardOutlinedIcon /></Link></div><div className="ecosystem-hero-art">{serviceCatalog.slice(0,6).map((service) => <ServiceArt key={service.slug} index={service.atlasIndex} />)}</div></section>
  <section className="ecosystem-section"><div className="ecosystem-section-head"><p className="private-kicker">SUPER APP EXPERIENCES</p><h2>Built around everyday life</h2><p>Choose an experience and discover everything connected to it.</p></div><div className="experience-grid">{serviceCatalog.map((service) => <Link className={`experience-card experience-${service.atlasIndex % 5}`} key={service.slug} to={service.live ? "/store" : `/app/services/${service.slug}`}><ServiceArt index={service.atlasIndex} /><div><span>{service.name}</span><h3>{service.experience}</h3><ul>{service.items.map((item) => <li key={item}>{item}</li>)}</ul></div><i><ArrowForwardOutlinedIcon /></i></Link>)}</div></section>
  <section className="ecosystem-section"><div className="ecosystem-section-head"><h2>Why SMAJ PI HUB?</h2></div><div className="why-grid">{why.map(([Icon,title,text]) => <article key={title}><Icon /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="experience-showcase"><div><p className="private-kicker">ONE SIMPLE EXPERIENCE</p><h2>Experience SMAJ PI HUB</h2><p>Everything connected in one simple experience.</p></div><div className="phone-carousel"><article><div className="phone-screen"><ServiceArt index={0} /><span>Discover</span></div><h3>Discover</h3><p>Explore all SMAJ PI HUB services</p></article><article><div className="phone-screen"><ServiceArt index={8} /><span>Connect</span></div><h3>Connect</h3><p>Access services and communities</p></article><article><div className="phone-screen"><ServiceArt index={14} /><span>Manage</span></div><h3>Manage</h3><p>Your account, wallet, and settings</p></article></div></section>
  <section className="ecosystem-section"><div className="ecosystem-section-head"><h2>Building the future of digital access</h2></div><div className="trust-growth-grid"><article><strong>Global Vision</strong><p>Connecting users and services worldwide</p></article><article><strong>Trusted Experience</strong><p>Designed with safety and transparency</p></article><article><strong>Continuous Growth</strong><p>New services and improvements over time</p></article></div></section>
  <section className="assistant-callout"><AutoAwesomeOutlinedIcon /><div><p className="private-kicker">SMAJ PI HUB AI ASSISTANT</p><h2>Your smart guide inside SMAJ PI HUB</h2><p>Find services, get help, and navigate faster.</p><div><span>“Find a service for me”</span><span>“Help me use SMAJ PI HUB”</span><span>“Show what I can do”</span></div></div><Link className="private-primary-button" to="/assistant">Open AI Assistant</Link></section>
  <section className="ecosystem-section"><div className="ecosystem-section-head"><h2>Need help?</h2><p>We are here for you.</p></div><div className="support-grid">{support.map(([Icon,title,text,items,to]) => <Link key={title} to={to}><Icon /><h3>{title}</h3><p>{text}</p><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></Link>)}</div></section>
  <footer className="private-home-footer"><div><strong>SMAJ PI HUB</strong><p>Connecting everyday services in one platform.</p></div><nav><Link to="/about">About</Link><Link to="/app/services">Services</Link><Link to="/help">Help Center</Link><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms of Service</Link><Link to="/contact">Contact</Link></nav><div><span>Part of the SMAJ Ecosystem</span><span>© 2026 SMAJ PI HUB. All rights reserved.</span></div></footer>
</main>;
export default DashboardPage;
