import { useMemo, useState, type FormEvent } from "react";
import SearchOutlinedIcon from "@mui/icons-material/SearchOutlined";
import ExpandMoreOutlinedIcon from "@mui/icons-material/ExpandMoreOutlined";

const categories = [
  ["Getting Started", ["Create account", "Use SMAJ PI HUB", "Explore services", "Profile setup"]],
  ["Marketplace Help", ["Buying", "Selling", "Payments", "Product safety", "Seller guide"]],
  ["Wallet & Payments", ["Connect wallet", "Disconnect wallet", "Transactions", "Payment issues"]],
  ["Account & Security", ["Protect account", "Login problems", "Privacy", "Report suspicious activity"]],
  ["Report Center", ["Report a problem", "Report user", "Report product", "Send feedback"]],
] as const;
const HelpCenterPage = () => { const [search, setSearch] = useState(""); const [open, setOpen] = useState(""); const [message, setMessage] = useState(""); const [submitted, setSubmitted] = useState(false); const filtered = useMemo(() => categories.map(([title,items]) => [title,items.filter((item) => item.toLowerCase().includes(search.toLowerCase()))] as const).filter(([,items]) => items.length), [search]); const submit = (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; setSubmitted(true); setMessage(""); }; return <main className="private-page help-center-page"><section className="help-hero"><p className="private-kicker">SMAJ PI HUB SUPPORT</p><h1>How can we help you?</h1><label><SearchOutlinedIcon /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search help articles..." /></label></section><section className="help-accordion">{filtered.map(([title,items]) => <article key={title}><h2>{title}</h2>{items.map((item) => <div key={item}><button onClick={() => setOpen(open === `${title}-${item}` ? "" : `${title}-${item}`)}><span>{item}</span><ExpandMoreOutlinedIcon /></button>{open === `${title}-${item}` ? <p>Find guidance for {item.toLowerCase()} across SMAJ PI HUB. For account-specific help, contact support below.</p> : null}</div>)}</article>)}</section><section className="support-form-section"><div><p className="private-kicker">CONTACT SUPPORT</p><h2>Still need help?</h2><p>Send the SMAJ support team a clear description of the issue.</p></div><form onSubmit={submit}><label>Topic<select><option>Account support</option><option>Marketplace</option><option>Wallet and payment</option><option>Safety report</option><option>Feedback</option></select></label><label>Message<textarea required rows={5} value={message} onChange={(event) => setMessage(event.target.value)} /></label><label>Screenshot upload<input type="file" accept="image/*" /></label>{submitted ? <div className="private-alert success">Support request submitted.</div> : null}<button className="private-primary-button">Submit</button></form></section></main>; };
export default HelpCenterPage;
