import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { useSearchParams } from "react-router-dom";
import { axiosClient } from "../../lib/axiosClient";
import { useAuthContext } from "../../contexts/AuthContext";
import type { ChatMessage, Conversation } from "../../types/marketplace";

type RichConversation = Conversation & { profileImage?: string; online?: boolean; demo?: boolean; displayTime?: string };
const now = new Date().toISOString();
const demos: RichConversation[] = [
  { _id:"demo-ahmed",buyerId:"demo-buyer",sellerId:"ahmed",productId:"demo-phone",productTitle:"iPhone 13 Pro",productImage:"https://picsum.photos/seed/iphone13chat/180/180",lastMessage:"Yes, the phone is still available.",updatedAt:now,buyerName:"You",sellerName:"Ahmed Electronics",unreadBy:["demo-user"],profileImage:"https://i.pravatar.cc/160?img=12",online:true,demo:true,displayTime:"2 min ago" },
  { _id:"demo-sarah",buyerId:"demo-buyer",sellerId:"sarah",productId:"demo-shoes",productTitle:"Nike Shoes",productImage:"https://picsum.photos/seed/nikeshoeschat/180/180",lastMessage:"I can deliver today.",updatedAt:now,buyerName:"You",sellerName:"Sarah Fashion",unreadBy:[],profileImage:"https://i.pravatar.cc/160?img=47",online:true,demo:true,displayTime:"15 min ago" },
  { _id:"demo-musa",buyerId:"demo-buyer",sellerId:"musa",productId:"demo-watch",productTitle:"Smart Watch",productImage:"https://picsum.photos/seed/smartwatchchat/180/180",lastMessage:"Payment received, order confirmed.",updatedAt:now,buyerName:"You",sellerName:"Musa Gadgets",unreadBy:[],profileImage:"https://i.pravatar.cc/160?img=33",online:false,demo:true,displayTime:"1 hour ago" },
  { _id:"demo-amina",buyerId:"demo-buyer",sellerId:"amina",productId:"demo-headphones",productTitle:"Wireless Headphones",productImage:"https://picsum.photos/seed/headphoneschat/180/180",lastMessage:"Thank you for buying from us.",updatedAt:now,buyerName:"You",sellerName:"Amina Store",unreadBy:[],profileImage:"https://i.pravatar.cc/160?img=44",online:true,demo:true,displayTime:"Yesterday" },
];
const demoMessages = (conversation: RichConversation): ChatMessage[] => [{ _id:`${conversation._id}-1`,conversationId:conversation._id,senderId:conversation.sellerId,message:`Hello, are you interested in ${conversation.productTitle}?`,createdAt:new Date(Date.now()-900000).toISOString(),readAt:now },{ _id:`${conversation._id}-2`,conversationId:conversation._id,senderId:"demo-user",message:"Yes. Is it still available and can you deliver?",createdAt:new Date(Date.now()-600000).toISOString(),readAt:now },{ _id:`${conversation._id}-3`,conversationId:conversation._id,senderId:conversation.sellerId,message:conversation.lastMessage || "Yes, it is available.",createdAt:new Date(Date.now()-120000).toISOString() }];
const MessagesPage = () => { const { user } = useAuthContext(); const [params, setParams] = useSearchParams(); const [conversations, setConversations] = useState<RichConversation[]>(demos); const [messages, setMessages] = useState<ChatMessage[]>([]); const [text, setText] = useState(""); const activeId = params.get("conversation") || conversations[0]?._id; const active = useMemo(() => conversations.find((item) => item._id === activeId), [activeId,conversations]);
  const loadConversations = useCallback(async () => { try { const { data } = await axiosClient.get("/messages"); setConversations([...data.conversations, ...demos]); } catch { setConversations(demos); } }, []); const loadMessages = useCallback(async () => { if (!activeId) return; if (activeId.startsWith("demo-")) { const conversation = demos.find((item) => item._id === activeId); if (conversation) setMessages(demoMessages(conversation)); return; } const { data } = await axiosClient.get(`/messages/${activeId}`); setMessages(data.messages); }, [activeId]);
  useEffect(() => { axiosClient.get("/messages").then(({ data }) => setConversations([...data.conversations,...demos])).catch(() => setConversations(demos)); const timer = window.setInterval(() => { void loadConversations(); },5000); return () => window.clearInterval(timer); }, [loadConversations]);
  useEffect(() => { if (!activeId) return; if (activeId.startsWith("demo-")) { const conversation = demos.find((item) => item._id === activeId); Promise.resolve(conversation ? demoMessages(conversation) : []).then(setMessages); } else { axiosClient.get(`/messages/${activeId}`).then(({ data }) => setMessages(data.messages)); } const timer = window.setInterval(() => { void loadMessages(); },4000); return () => window.clearInterval(timer); }, [activeId,loadMessages]);
  const send = async (event: FormEvent) => { event.preventDefault(); if (!activeId || !text.trim()) return; const message = text.trim(); setText(""); if (activeId.startsWith("demo-")) { setMessages((items) => [...items,{ _id:`demo-${Date.now()}`,conversationId:activeId,senderId:user?.uid || "demo-user",message,createdAt:new Date().toISOString(),readAt:new Date().toISOString() }]); return; } await axiosClient.post(`/messages/${activeId}`,{ message }); await Promise.all([loadMessages(),loadConversations()]); };
  return <main className="private-page messages-page"><section className="private-page-head"><div><p className="private-kicker">COMMUNICATION CENTER</p><h1>Messages</h1><p>Buyer and seller conversations across SMAJ PI HUB.</p></div></section><section className="messages-layout rich"><aside className="conversation-list">{conversations.map((item) => <button className={item._id === activeId ? "active" : ""} key={item._id} onClick={() => setParams({ conversation:item._id })}><span className="conversation-avatar">{item.profileImage ? <img src={item.profileImage} alt="" /> : (item.sellerName || item.buyerName || "U").slice(0,1)}<i className={item.online ? "online" : "offline"} /></span><div><strong>{item.sellerId === user?.uid ? item.buyerName : item.sellerName}</strong><p>{item.lastMessage}</p><small>{item.productTitle} · {item.displayTime || new Date(item.updatedAt).toLocaleString()}</small></div>{item.unreadBy?.length ? <b>{item.unreadBy.length}</b> : null}</button>)}</aside><div className="chat-panel">{active ? <><header><div className="chat-person"><span className="conversation-avatar">{active.profileImage ? <img src={active.profileImage} alt="" /> : active.sellerName?.slice(0,1)}<i className={active.online ? "online" : "offline"} /></span><div><strong>{active.sellerId === user?.uid ? active.buyerName : active.sellerName}</strong><small>{active.online ? "Online" : "Offline"}</small></div></div><div className="chat-product-preview">{active.productImage ? <img src={active.productImage} alt="" /> : null}<span><strong>{active.productTitle}</strong><small>Marketplace conversation</small></span></div></header><div className="chat-messages">{messages.map((item) => <article className={item.senderId === user?.uid || item.senderId === "demo-user" ? "mine" : ""} key={item._id}><p>{item.message}</p><small>{new Date(item.createdAt).toLocaleTimeString([], { hour:"2-digit",minute:"2-digit" })}{item.senderId === user?.uid || item.senderId === "demo-user" ? ` · ${item.readAt ? "Read" : "Sent"}` : ""}</small></article>)}{active.online ? <div className="typing-indicator"><i /><i /><i /><span>Typing</span></div> : null}</div><form onSubmit={send}><input value={text} onChange={(event) => setText(event.target.value)} maxLength={1000} placeholder="Write a message..." /><button className="private-primary-button">Send</button></form></> : <div className="private-state">Select a conversation.</div>}</div></section></main>; };
export default MessagesPage;
