import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { axiosClient } from "../../lib/axiosClient";
import type { Product, Review, SellerSummary } from "../../types/marketplace";
import MarketplaceProductCard from "../../components/MarketplaceProductCard";
import PrivateSkeleton from "../../components/PrivateSkeleton";
import TrustBadge from "../../components/TrustBadge";
const SellerProfilePage = () => { const { id } = useParams(); const [data, setData] = useState<{ seller: SellerSummary; products: Product[]; reviews: Review[] } | null>(null); const [error, setError] = useState(""); useEffect(() => { axiosClient.get(`/marketplace/sellers/${id}`).then(({ data }) => setData(data)).catch(() => setError("Seller profile not found.")); }, [id]); if (!data) return <main className="private-page">{error ? <div className="private-state error">{error}</div> : <PrivateSkeleton variant="seller" />}</main>; return <main className="private-page seller-profile-page"><section className="seller-profile-hero"><div className="profile-avatar seller-profile-avatar">{data.seller.avatar ? <img src={data.seller.avatar} alt="" /> : data.seller.displayName.slice(0, 1).toUpperCase()}</div><div><p className="private-kicker">SELLER PROFILE</p><h1 className="profile-name-line"><span className="profile-name-text">{data.seller.displayName}</span><TrustBadge level={data.seller.verificationLevel} /></h1><p>@{data.seller.piUsername || data.seller.username}</p><Link className="private-secondary-button" to="/report-abuse">Report seller</Link></div><div className="seller-profile-stats"><strong>{data.products.length}<span>Products</span></strong><strong>{data.seller.successfulOrders || 0}<span>Successful orders</span></strong><strong>{data.seller.averageRating?.toFixed(1) || "New"}<span>Rating</span></strong></div></section><p className="seller-joined">Joined {data.seller.createdAt ? new Date(data.seller.createdAt).toLocaleDateString() : "recently"}</p><section className="section-title"><div><h2>Products listed</h2></div></section><section className="product-grid">{data.products.map((product) => <MarketplaceProductCard key={product._id} product={product} />)}</section><section className="reviews-panel"><div className="section-title"><div><h2>Buyer reviews</h2><p>{data.reviews.length ? `${data.reviews.length} marketplace reviews` : "No reviews yet"}</p></div></div>{data.reviews.map((review) => <article key={review._id}><strong>{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</strong><p>{review.message || "Positive completed order."}</p><small>{review.buyerName} · {new Date(review.createdAt).toLocaleDateString()}</small></article>)}</section></main>; };
export default SellerProfilePage;
