import { useEffect, useState, type FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { useAuthContext } from "../../contexts/AuthContext";
import ConfirmSignOutModal from "../../components/ConfirmSignOutModal";

const SettingsPage = () => { const { user, updateSettings, updateProfile, signOut } = useAuthContext(); const navigate = useNavigate(); const [appearance, setAppearance] = useState<"light" | "dark" | "system">(user?.settings?.theme || "light"); const [language, setLanguage] = useState(user?.settings?.language || "English"); const [country, setCountry] = useState(user?.country || ""); const [messageNotifications, setMessageNotifications] = useState(user?.settings?.notifications ?? true); const [orderNotifications, setOrderNotifications] = useState(user?.settings?.notifications ?? true); const [message, setMessage] = useState(""); const [showSignOut, setShowSignOut] = useState(false);
  useEffect(() => { const resolved = appearance === "system" ? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light") : appearance; document.documentElement.dataset.privateTheme = resolved; }, [appearance]);
  const save = async (event: FormEvent) => { event.preventDefault(); try { const resolved = appearance === "system" ? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light") : appearance; await Promise.all([updateSettings({ theme: resolved, language, notifications: messageNotifications || orderNotifications }), updateProfile({ displayName: user?.displayName || user?.username || "Pi user", country, contactPhone: user?.contactPhone || "", role: user?.role || "buyer", avatar: user?.avatar })]); setMessage("Settings saved."); } catch { setMessage("Could not save settings."); } };
  const logout = async () => { await signOut(); navigate("/home", { replace: true }); };
  return <main className="private-page"><section className="private-page-head"><div><p className="private-kicker">ACCOUNT</p><h1>Settings</h1><p>Manage account, security, notifications, appearance, and data preferences.</p></div></section><form className="settings-sections" onSubmit={(event) => void save(event)}>
    <section><h2>Account</h2><p>Personal information and regional preferences.</p><label>Display name<input value={user?.displayName || user?.username || ""} disabled /></label><div className="private-form-row"><label>Language<select value={language} onChange={(event) => setLanguage(event.target.value)}><option>English</option><option>French</option><option>Spanish</option><option>Portuguese</option><option>Arabic</option></select></label><label>Country<input value={country} onChange={(event) => setCountry(event.target.value)} /></label></div></section>
    <section><h2>Security</h2><p>Review your current Pi-authenticated session.</p><div className="settings-info-row"><span>Login activity</span><strong>Current Pi Browser session</strong></div><div className="settings-info-row"><span>Connected devices</span><strong>This device</strong></div><div className="settings-info-row"><span>Privacy</span><strong>Marketplace profile</strong></div></section>
    <section><h2>Notifications</h2><label className="setting-line"><span><strong>Message notifications</strong><small>Alerts for buyer and seller messages.</small></span><input type="checkbox" checked={messageNotifications} onChange={(event) => setMessageNotifications(event.target.checked)} /></label><label className="setting-line"><span><strong>Order notifications</strong><small>Updates for orders, payments, and fulfillment.</small></span><input type="checkbox" checked={orderNotifications} onChange={(event) => setOrderNotifications(event.target.checked)} /></label></section>
    <section><h2>Appearance</h2><div className="appearance-options">{(["light", "dark", "system"] as const).map((mode) => <button type="button" className={appearance === mode ? "active" : ""} key={mode} onClick={() => setAppearance(mode)}>{mode}</button>)}</div></section>
    <section><h2>Data</h2><div className="settings-info-row"><span>Account data</span><button type="button" className="private-secondary-button" onClick={() => setMessage("Account data export request recorded.")}>Request export</button></div><div className="settings-info-row"><span>Delete account request</span><button type="button" className="private-secondary-button danger" onClick={() => setMessage("Delete account request requires support review.")}>Request deletion</button></div></section>
    {message ? <div className="private-alert">{message}</div> : null}<button className="private-primary-button">Save Settings</button></form><section className="danger-card"><div><h2>Logout</h2><p>End this session on the current device.</p></div><button className="private-secondary-button danger" onClick={() => setShowSignOut(true)}>Logout</button></section><ConfirmSignOutModal open={showSignOut} onCancel={() => setShowSignOut(false)} onConfirm={() => void logout()} /></main>;
}; export default SettingsPage;
