import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import AddIcon from "@mui/icons-material/Add";
import { axiosClient } from "../../lib/axiosClient";
import type { Product } from "../../types/marketplace";
import MarketplaceProductCard from "../../components/MarketplaceProductCard";

const STORE_CATEGORIES=["Electronics","Fashion","Vehicles","Home","Property","Phones","Computers","Beauty","Services","Others"];
const demoNames=["Wireless Earbuds","Smart Watch","Portable Speaker","Classic Sneakers","Travel Backpack","Android Phone","Laptop Computer","Skincare Set","Modern Sofa","City Bicycle","Kitchen Blender","Office Chair","Summer Dress","Gaming Mouse","Power Bank","Digital Camera","Apartment Listing","Car Rental","Graphic Design Service","Fresh Food Box"];
const demoLocations=["Lagos, Nigeria","Abuja, Nigeria","Kano, Nigeria","Accra, Ghana","Nairobi, Kenya","Dakar, Senegal","Johannesburg, South Africa","London, UK"];
const demoImageKeyword:Record<string,string>={Electronics:"electronics",Fashion:"fashion",Vehicles:"car",Home:"furniture",Property:"house",Phones:"smartphone",Computers:"laptop",Beauty:"beauty",Services:"business",Others:"shopping"};
const DEMO_PRODUCTS:Product[]=Array.from({length:500},(_,index)=>{const category=STORE_CATEGORIES[index%STORE_CATEGORIES.length];const title=`${demoNames[index%demoNames.length]} ${Math.floor(index/demoNames.length)+1}`;const pricePi=Number((0.0005+((index*137)%145)/10000).toFixed(4));return{_id:`demo-product-${index+1}`,sellerId:"smaj-demo-store",sellerName:["SMAJ Market","Amina Store","Ahmed Electronics","Musa Gadgets"][index%4],piUsername:"smajmarket",title,image:`https://loremflickr.com/640/480/${demoImageKeyword[category]}?lock=${index+1}`,images:[`https://loremflickr.com/900/700/${demoImageKeyword[category]}?lock=${index+1}`,`https://loremflickr.com/900/700/${demoImageKeyword[category]}?lock=${index+501}`],pricePi,description:`${title} from a trusted SMAJ PI HUB demo seller. Contact the seller for availability and delivery details.`,category,location:demoLocations[index%demoLocations.length],sellerContact:"@smajmarket",active:true,approved:true,createdAt:new Date(Date.now()-index*3600000).toISOString(),rating:Number((4.1+(index%9)/10).toFixed(1))};});

const StorePage=()=>{const[params]=useSearchParams();const[products,setProducts]=useState<Product[]>([]);const[savedIds,setSavedIds]=useState<string[]>([]);const[loading,setLoading]=useState(true);const[usingFallback,setUsingFallback]=useState(false);const[search,setSearch]=useState(params.get("search")||"");const[category,setCategory]=useState(params.get("category")||"All");const[location,setLocation]=useState("");const[sort,setSort]=useState("newest");
  useEffect(()=>{Promise.all([axiosClient.get<{products:Product[]}>("/marketplace/products"),axiosClient.get<{products:Product[]}>("/marketplace/saved")]).then(([all,saved])=>{const live=all.data.products||[];setProducts(live.length?live:DEMO_PRODUCTS);setSavedIds(saved.data.products.map((item)=>item._id));setUsingFallback(!live.length);}).catch(()=>{setProducts(DEMO_PRODUCTS);setUsingFallback(true);}).finally(()=>setLoading(false));},[]);
  const visibleProducts=useMemo(()=>{const query=search.trim().toLowerCase();const place=location.trim().toLowerCase();return products.filter((p)=>(category==="All"||p.category===category)&&(!place||p.location.toLowerCase().includes(place))&&(!query||[p.title,p.sellerName,p.category].join(" ").toLowerCase().includes(query))).sort((a,b)=>sort==="price-low"?a.pricePi-b.pricePi:sort==="price-high"?b.pricePi-a.pricePi:+new Date(b.createdAt)-+new Date(a.createdAt));},[category,location,products,search,sort]);
  const toggleFavorite=async(product:Product)=>{if(product._id.startsWith("demo-product-")){setSavedIds((current)=>current.includes(product._id)?current.filter((id)=>id!==product._id):[...current,product._id]);return;}const{data}=await axiosClient.post<{saved:boolean}>(`/marketplace/products/${product._id}/favorite`);setSavedIds((current)=>data.saved?[...new Set([...current,product._id])]:current.filter((id)=>id!==product._id));};
  return <main className="private-page"><section className="private-page-head"><div><p className="private-kicker">MARKETPLACE</p><h1>SMAJ Store</h1><p>Find trusted products and services offered by the Pi community.</p></div><Link className="private-primary-button" to="/add-product"><AddIcon/> Add Product</Link></section><section className="category-strip">{["All",...STORE_CATEGORIES].map((item)=><button className={category===item?"active":""} key={item} onClick={()=>setCategory(item)}>{item}</button>)}</section><section className="store-tools"><label><span>Search</span><input type="search" value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Product name"/></label><label><span>Location</span><input value={location} onChange={(event)=>setLocation(event.target.value)} placeholder="City or country"/></label><label><span>Sort</span><select value={sort} onChange={(event)=>setSort(event.target.value)}><option value="newest">Newest</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label></section>{loading?<div className="private-state">Loading products...</div>:null}{usingFallback?<div className="private-alert">Showing SMAJ Store demo products while the live catalog reconnects.</div>:null}{!loading&&!visibleProducts.length?<div className="private-state"><h2>No matching products</h2><p>Try another search, category, or location.</p></div>:<section className="product-grid">{visibleProducts.map((product)=><MarketplaceProductCard key={product._id} product={product} saved={savedIds.includes(product._id)} onFavorite={(item)=>void toggleFavorite(item)}/>)}</section>}</main>;
};
export default StorePage;
