import { useEffect, useState, type FormEvent } from "react";
import VideoCallRoundedIcon from "@mui/icons-material/VideoCallRounded";
import ContentCopyRoundedIcon from "@mui/icons-material/ContentCopyRounded";
import { createLiveInput, getCreatorLiveInputs, getLiveInputStatus, type CreatorLiveInput, type LiveCredentials } from "../../lib/streamLive";

const StreamLiveSetup = () => {
  const [title, setTitle] = useState("");
  const [chatMode, setChatMode] = useState("enabled");
  const [credentials, setCredentials] = useState<LiveCredentials | null>(null);
  const [created, setCreated] = useState<CreatorLiveInput | null>(null);
  const [history, setHistory] = useState<CreatorLiveInput[]>([]);
  const [state, setState] = useState<"idle" | "creating" | "error">("idle");
  const [message, setMessage] = useState("");
  useEffect(() => { void getCreatorLiveInputs().then(setHistory).catch(() => undefined); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); try { setState("creating"); setMessage(""); const live = await createLiveInput({ title, chatMode }); setCreated(live); setCredentials(live.credentials); setHistory(items => [live, ...items]); setMessage("Live input created. Copy the OBS credentials below before leaving this page."); setState("idle"); } catch (error) { setState("error"); setMessage((error as { response?: { data?: { message?: string } } }).response?.data?.message || "The live input could not be created."); } };
  const copy = async (value: string, label: string) => { await navigator.clipboard.writeText(value); setMessage(`${label} copied.`); };
  const refresh = async (live: CreatorLiveInput) => { try { const result = await getLiveInputStatus(live.liveInputUid); setHistory(items => items.map(item => item.liveInputUid === live.liveInputUid ? { ...item, processingStatus: result.status } : item)); setMessage(result.status === "live" ? "Broadcast detected. Your stream is live." : "Cloudflare is ready, but OBS is not broadcasting yet."); } catch (error) { setState("error"); setMessage((error as { response?: { data?: { message?: string } } }).response?.data?.message || "Live status could not be refreshed."); } };
  if (credentials && created) return <div className="sw-live-created"><header><VideoCallRoundedIcon /><div><span>LIVE INPUT READY</span><h2>{created.title}</h2><p>Use these credentials in OBS. The stream key is secret and is shown only in this setup response.</p></div></header><section><label>OBS Server (RTMPS)<div><code>{credentials.rtmpsUrl}</code><button onClick={() => void copy(credentials.rtmpsUrl, "Server URL")}><ContentCopyRoundedIcon /> Copy</button></div></label><label>Stream Key<div><code className="secret">{credentials.streamKey}</code><button onClick={() => void copy(credentials.streamKey, "Stream key")}><ContentCopyRoundedIcon /> Copy</button></div></label></section><ol><li>Open OBS Studio, then Settings, then Stream.</li><li>Choose Service: Custom.</li><li>Paste the Server and Stream Key shown above.</li><li>Click Start Streaming in OBS.</li><li>Return here and check status. Admin approval, Public visibility and Playback must be enabled before viewers can watch.</li></ol><div className="sw-live-created-actions"><button onClick={() => void refresh(created)}>Check live status</button><button onClick={() => { setCredentials(null); setCreated(null); setTitle(""); }}>Create another</button></div>{message ? <p>{message}</p> : null}</div>;
  return <><form className="sw-form sw-live-form" onSubmit={submit}><div className="sw-live-setup"><VideoCallRoundedIcon /><h2>Set up your live stream</h2><p>Create secure RTMPS credentials for OBS and record the broadcast automatically.</p></div><label>Stream title<input value={title} minLength={3} maxLength={140} required onChange={event => setTitle(event.target.value)} placeholder="What are you streaming?" /></label><div><label>Start<select disabled><option>Go live with OBS</option></select></label><label>Chat<select value={chatMode} onChange={event => setChatMode(event.target.value)}><option value="enabled">Enabled</option><option value="followers">Followers only</option><option value="disabled">Disabled</option></select></label></div>{message ? <p className={`sw-upload-message ${state === "error" ? "error" : "success"}`}>{message}</p> : null}<button type="submit" disabled={state === "creating"}>{state === "creating" ? "Creating secure input..." : "Create live input"}</button></form>{history.length ? <section className="sw-live-history"><h2>Your live inputs</h2>{history.map(live => <article key={live.liveInputUid}><div><b>{live.title}</b><small>{live.moderationStatus}  -  {live.visibility}  -  {live.processingStatus}</small></div><button onClick={() => void refresh(live)}>Refresh status</button></article>)}</section> : null}</>;
};

export default StreamLiveSetup;
