import { useEffect, useState, type FormEvent } from "react";
import CheckCircleRoundedIcon from "@mui/icons-material/CheckCircleRounded";
import PersonOutlineRoundedIcon from "@mui/icons-material/PersonOutlineRounded";
import { getStreamProfile, saveStreamProfile, type StreamProfile } from "../../lib/streamProfile";

const genres = ["action", "anime", "comedy", "documentary", "drama", "family", "horror", "music", "romance", "sports", "thriller"];
const regions = ["african", "bollywood", "chinese", "hollywood", "k-drama", "kannywood", "nollywood"];

const StreamProfilePanel = () => {
  const [profile, setProfile] = useState<StreamProfile | null>(null);
  const [username, setUsername] = useState("");
  const [completion, setCompletion] = useState(0);
  const [state, setState] = useState<"loading" | "ready" | "saving" | "error">("loading");
  const [message, setMessage] = useState("");
  useEffect(() => { void getStreamProfile().then((data) => { setProfile(data.profile); setUsername(data.username || ""); setCompletion(data.completion); setState("ready"); }).catch(() => { setState("error"); setMessage("Your Stream profile could not be loaded."); }); }, []);
  const change = <K extends keyof StreamProfile>(key: K, value: StreamProfile[K]) => setProfile((current) => current ? { ...current, [key]: value } : current);
  const toggle = (key: "favoriteGenres" | "preferredRegions", value: string) => setProfile((current) => current ? { ...current, [key]: current[key].includes(value) ? current[key].filter((item) => item !== value) : [...current[key], value] } : current);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!profile) return; try { setState("saving"); setMessage(""); const data = await saveStreamProfile(profile); setProfile(data.profile); setCompletion(data.completion); setState("ready"); setMessage("Stream profile saved and synchronized."); } catch (error) { setState("error"); setMessage((error as { response?: { data?: { message?: string } } }).response?.data?.message || "Profile could not be saved."); } };
  if (state === "loading") return <div className="sw-catalog-status">Loading your Stream profile…</div>;
  if (!profile) return <div className="sw-catalog-status warning">{message}</div>;
  return <form className="sw-profile" onSubmit={(event) => void submit(event)}>
    <section className="sw-profile-summary"><div className="sw-profile-avatar">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="" /> : <PersonOutlineRoundedIcon />}</div><div><h2>{profile.displayName || "Your Stream profile"}</h2><p>{username ? `@${username}` : "SMAJ Stream viewer"}</p><span>{completion === 100 ? <><CheckCircleRoundedIcon /> Profile complete</> : `${completion}% complete`}</span></div><div className="sw-profile-meter"><i style={{ width: `${completion}%` }} /></div></section>
    <section className="sw-profile-card"><header><h2>Viewer identity</h2><p>How you appear across SMAJ Stream.</p></header><div className="sw-profile-fields"><label>Display name<input value={profile.displayName} minLength={2} maxLength={80} required onChange={(event) => change("displayName", event.target.value)} /></label><label>Avatar HTTPS URL<input type="url" value={profile.avatarUrl} placeholder="https://…" onChange={(event) => change("avatarUrl", event.target.value)} /></label><label>Country code<input value={profile.country} maxLength={2} placeholder="NG" onChange={(event) => change("country", event.target.value.toUpperCase())} /></label><label>Interface language<select value={profile.language} onChange={(event) => change("language", event.target.value)}><option value="en">English</option><option value="fr">French</option><option value="ar">Arabic</option><option value="ha">Hausa</option><option value="hi">Hindi</option><option value="ko">Korean</option><option value="zh">Chinese</option></select></label><label>Subtitle language<select value={profile.subtitleLanguage} onChange={(event) => change("subtitleLanguage", event.target.value)}><option value="en">English</option><option value="fr">French</option><option value="ar">Arabic</option><option value="ha">Hausa</option><option value="hi">Hindi</option></select></label><label>Maturity level<select value={profile.maturityLevel} onChange={(event) => change("maturityLevel", event.target.value as StreamProfile["maturityLevel"])}><option value="kids">Kids</option><option value="13">13+</option><option value="16">16+</option><option value="18">18+</option></select></label></div></section>
    <section className="sw-profile-card"><header><h2>What you enjoy</h2><p>Choose at least three genres for better recommendations.</p></header><h3>Favorite genres</h3><div className="sw-choice-grid">{genres.map((item) => <button type="button" className={profile.favoriteGenres.includes(item) ? "active" : ""} onClick={() => toggle("favoriteGenres", item)} key={item}>{item}</button>)}</div><h3>Preferred regions</h3><div className="sw-choice-grid">{regions.map((item) => <button type="button" className={profile.preferredRegions.includes(item) ? "active" : ""} onClick={() => toggle("preferredRegions", item)} key={item}>{item}</button>)}</div></section>
    <section className="sw-profile-card"><header><h2>Playback and privacy</h2><p>Control quality, data usage and activity visibility.</p></header><label className="sw-profile-quality">Preferred quality<select value={profile.videoQuality} onChange={(event) => change("videoQuality", event.target.value as StreamProfile["videoQuality"])}><option value="auto">Automatic</option><option value="data-saver">Data saver</option><option value="hd">HD</option><option value="full-hd">Full HD</option></select></label>{[["autoplay","Autoplay next episode"],["dataSaver","Use less mobile data"],["showActivity","Show my viewing activity"],["emailNotifications","Email entertainment updates"]].map(([key,label]) => <label className="sw-profile-toggle" key={key}><span>{label}</span><input type="checkbox" checked={Boolean(profile[key as keyof StreamProfile])} onChange={(event) => change(key as "autoplay", event.target.checked)} /><i /></label>)}</section>
    {message ? <p className={`sw-profile-message ${state === "error" ? "error" : ""}`}>{message}</p> : null}<button className="sw-profile-save" type="submit" disabled={state === "saving"}>{state === "saving" ? "Saving…" : "Save Stream profile"}</button>
  </form>;
};

export default StreamProfilePanel;
