import {colors,radii,spacing} from "@smaj/design-tokens";
import {useFocusEffect,useRouter} from "expo-router";
import {useCallback,useMemo,useState} from "react";
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {api} from "@/lib/api";import {useAuth} from "@/providers/auth-provider";import type {Conversation} from "@/types/messaging";
export default function Messages(){const router=useRouter(),{user,beginPiSignIn}=useAuth();const [all,setAll]=useState<Conversation[]>([]),[q,setQ]=useState(""),[arch,setArch]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
const load=useCallback(async()=>{if(!user)return;setBusy(true);try{const r=await api.request<{conversations:Conversation[]}>("/messages");setAll(r.conversations);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load messages")}finally{setBusy(false)}},[user]);useFocusEffect(useCallback(()=>{void load()},[load]));
const shown=useMemo(()=>all.filter(x=>!!x.archived===arch&&[x.participantName,x.productTitle,x.lastMessage].join(" ").toLowerCase().includes(q.toLowerCase())),[all,arch,q]);
return <SafeAreaView style={s.safe} edges={["top"]}><View style={s.head}><Text style={s.eye}>ONE SHARED INBOX</Text><Text style={s.title}>Messages</Text></View>{!user?<View style={s.empty}><Text style={s.emptyTitle}>Continue with Pi</Text><Text style={s.muted}>Use the same conversations on Android and Pi Browser.</Text><Pressable style={s.primary} onPress={()=>void beginPiSignIn()}><Text style={s.white}>Continue with Pi</Text></Pressable></View>:<ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()}/>}>
<TextInput style={s.search} value={q} onChangeText={setQ} placeholder="Search conversations"/><View style={s.tabs}>{[false,true].map(v=><Pressable key={String(v)} style={[s.tab,arch===v&&s.active]} onPress={()=>setArch(v)}><Text style={arch===v?s.white:s.muted}>{v?"Archived":"Inbox"}</Text></Pressable>)}</View>{error?<Text style={s.error}>{error}</Text>:null}{busy&&!all.length?<ActivityIndicator color={colors.primary}/>:null}{!busy&&!shown.length?<View style={s.empty}><Text style={s.emptyTitle}>{arch?"No archived chats":"Your inbox is ready"}</Text></View>:null}{shown.map(x=>{const unread=!!user.uid&&x.unreadBy?.includes(user.uid);return <Pressable key={x._id} style={s.row} onPress={()=>router.push({pathname:"/messages/[id]",params:{id:x._id}})}><View style={s.avatar}><Text style={s.avatarText}>{(x.participantName||"S")[0]}</Text></View><View style={s.body}><View style={s.top}><Text numberOfLines={1} style={[s.name,unread&&s.bold]}>{x.participantName||"SMAJ member"} {x.online?"•":""}</Text><Text style={s.date}>{x.updatedAt?new Date(x.updatedAt).toLocaleDateString():""}</Text></View><Text style={s.product}>{x.productTitle||"SMAJ PI HUB"}</Text><Text numberOfLines={1} style={[s.preview,unread&&s.bold]}>{x.typing?"Typing...":x.lastMessage||"Start the conversation"}</Text></View>{unread?<View style={s.dot}/>:null}</Pressable>})}</ScrollView>}</SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},head:{padding:spacing.lg,backgroundColor:colors.surface,borderBottomWidth:1,borderColor:colors.border},eye:{fontSize:10,fontWeight:"900",letterSpacing:1,color:colors.primary},title:{fontSize:24,fontWeight:"900",color:colors.text},content:{padding:spacing.lg,paddingBottom:110,gap:spacing.md},search:{height:46,paddingHorizontal:16,borderRadius:radii.pill,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},tabs:{flexDirection:"row",gap:8},tab:{paddingHorizontal:18,paddingVertical:9,borderRadius:radii.pill,backgroundColor:colors.surface},active:{backgroundColor:colors.primary},white:{color:"#fff",fontWeight:"900"},row:{flexDirection:"row",alignItems:"center",gap:12,padding:12,borderRadius:radii.md,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface},avatar:{width:50,height:50,borderRadius:25,alignItems:"center",justifyContent:"center",backgroundColor:colors.surfaceMuted},avatarText:{fontSize:18,fontWeight:"900",color:colors.primary},body:{flex:1,gap:2},top:{flexDirection:"row"},name:{flex:1,fontWeight:"700",color:colors.text},bold:{fontWeight:"900",color:colors.text},date:{fontSize:10,color:colors.textMuted},product:{fontSize:11,fontWeight:"800",color:colors.primary},preview:{fontSize:13,color:colors.textMuted},dot:{width:9,height:9,borderRadius:5,backgroundColor:colors.primary},empty:{flex:1,minHeight:250,alignItems:"center",justifyContent:"center",gap:12,padding:24},emptyTitle:{fontSize:19,fontWeight:"900",color:colors.text},muted:{color:colors.textMuted,textAlign:"center"},primary:{paddingHorizontal:22,paddingVertical:13,borderRadius:radii.pill,backgroundColor:colors.primary},error:{padding:12,color:colors.danger}});
