export type EducationCourse = {
  id: string;
  title: string;
  provider: string;
  category: string;
  level: string;
  duration: string;
  priceUsdt: number;
  rating: string;
  enrollmentCount?: number;
  image: string;
  description?: string;
};

export type EducationPartner = {
  id: string;
  name: string;
  type: string;
  location: string;
  programs: string;
  status: string;
};

export type EducationCategory = string;

export type University = {
  id: string;
  slug: string;
  official_name: string;
  short_name?: string;
  local_name?: string;
  logo_url?: string;
  cover_image_url?: string;
  brand_primary_color?: string;
  description?: string;
  institution_type: string;
  founded_year?: number;
  country: string;
  country_code: string;
  state_region?: string;
  city?: string;
  address?: string;
  postal_code?: string;
  latitude?: number;
  longitude?: number;
  official_website?: string;
  admissions_website?: string;
  contact_email?: string;
  contact_phone?: string;
  languages?: string[];
  recognition_status: string;
  recognition_authority?: string;
  external_ids: Array<{ provider: string; id: string }>;
  whed_id?: string;
  partnership_status: string;
  partner_since?: string;
  pi_payments_enabled: boolean;
  applications_enabled: boolean;
  profile_claimed: boolean;
  claimed_by_user_id?: string;
  data_last_verified_at?: string;
  created_at: string;
  updated_at: string;
  is_demo: boolean;
};

export type UniversityProgram = {
  id: string;
  university_id: string;
  university_slug: string;
  name: string;
  degree_level: string;
  field: string;
  faculty?: string;
  department?: string;
  description?: string;
  duration?: string;
  study_mode: string;
  campus?: string;
  teaching_language?: string;
  tuition?: number;
  tuition_currency?: string;
  application_fee?: number;
  application_fee_currency?: string;
  admission_requirements?: string;
  intake?: string[];
  application_opening_date?: string;
  application_deadline?: string;
  official_program_url?: string;
  provenance: {
    source_type: string;
    source_name: string;
    source_url: string;
    external_id?: string;
    retrieved_at: string;
    last_verified_at: string;
    verification_status: string;
    confidence: number;
    is_official_source: boolean;
  };
  last_verified_at?: string;
  created_at: string;
  updated_at: string;
  is_demo: boolean;
};

export type UniversityClaim = {
  id: string;
  university_id: string;
  university_slug: string;
  university_name: string;
  representative_full_name: string;
  job_title: string;
  institutional_email: string;
  department?: string;
  phone?: string;
  university_website?: string;
  proof_of_authority: string;
  supporting_documents?: string[];
  message?: string;
  submitted_at: string;
  review_status: string;
  reviewed_by?: string;
  reviewed_at?: string;
  review_notes?: string;
  created_at: string;
  updated_at: string;
};

export type UniversityApplication = {
  id: string;
  application_id: string;
  applicant_id: string;
  university_id: string;
  university_slug: string;
  program_id?: string;
  program_name?: string;
  intake?: string;
  personal_information: Record<string, unknown>;
  education_history: Record<string, unknown>[];
  required_documents: Record<string, unknown>[];
  statement_essay?: string;
  status: string;
  payment_status: string;
  payment_id?: string;
  university_review_status?: string;
  submitted_at?: string;
  decision_at?: string;
  decision_notes?: string;
  created_at: string;
  updated_at: string;
};

export type UniversityPayment = {
  id: string;
  payment_id: string;
  user_id: string;
  university_id: string;
  university_slug: string;
  application_id?: string;
  program_id?: string;
  program_name?: string;
  payment_purpose: string;
  amount_display: number;
  currency_display: string;
  amount_pi: number;
  pi_payment_identifier?: string;
  transaction_identifier?: string;
  status: string;
  approved_at?: string;
  completed_at?: string;
  failed_at?: string;
  cancelled_at?: string;
  failure_reason?: string;
  audit_metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
};

export type UniversityAuthorization = {
  applications_enabled: boolean;
  pi_payments_enabled: boolean;
  payment_categories: string[];
};
