import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../src/pages/jobs/JobsPage.tsx", import.meta.url), "utf8");
const api = readFileSync(new URL("../src/lib/jobsApi.ts", import.meta.url), "utf8");
const header = readFileSync(new URL("../src/pages/jobs/JobsHeader.tsx", import.meta.url), "utf8");
const preferences = readFileSync(new URL("../src/pages/jobs/JobPreferencesPanel.tsx", import.meta.url), "utf8");
const styles = readFileSync(new URL("../src/pages/jobs/JobsPage.css", import.meta.url), "utf8");

assert.match(page, /Loading live opportunities/);
assert.match(page, /limited offline catalog/);
assert.match(page, /URLSearchParams/);
assert.match(api, /location\?: string/);

assert.match(page, /saveJobsProfile/);
assert.doesNotMatch(page, /localStorage\.setItem\("smaj_jobs_profile"/);
assert.match(page, /updateEmployerApplication/);
assert.match(page, /Submit company for review/);
assert.match(header, /pointerdown/);
assert.match(header, /event\.key === "Escape"/);
assert.match(header, /jobs-menu-backdrop/);
assert.match(header, /setMenuOpen\(value => !value\)/);
assert.doesNotMatch(header, /My professional profile/);
assert.match(header, /Employer dashboard/);
assert.match(header, /workspaceMode === "employer"/);
assert.match(header, /Find work/);
assert.match(header, /Hire talent/);
assert.match(page, /activeWorkspaceMode === "candidate"/);
assert.match(page, /SMAJ PI HUB/);
assert.match(page, /Add another company/);
assert.match(page, /newCompanyName/);
assert.match(page, /no separate Jobs login is needed/);
assert.doesNotMatch(page, /Sign in with your Pi account/);
assert.match(page, /Your SMAJ PI HUB photo and identity/);
assert.match(page, /profile-country-options/);
assert.match(page, /Search for your country/);
assert.match(page, /Profile saved to your SMAJ account/);
assert.match(page, /jobs-quick-search/);
assert.match(page, /Country, city or remote/);
assert.match(page, /Recommended jobs/);
assert.match(page, /recommendedJobs/);
assert.match(page, /jobs-search-sheet/);
assert.match(page, /Search suggestions/);
assert.match(page, /smaj_jobs_recent_searches/);
assert.match(page, /jobSearchSuggestions/);
assert.match(page, /locationSheetOpen/);
assert.match(page, /locationSuggestions/);
assert.match(page, /Your location/);
assert.match(page, /Search city, country, or remote/);
assert.match(page, /formatJobCompensation/);
assert.match(page, /salaryFromUsdt\(2200, 3000, "mo"\)/);
assert.match(styles, /--green: #6d3df5/);
assert.match(page, /Post your first job/);
assert.match(page, /jobs-search-employer-cta/);
assert.match(preferences, /How do you want to use SMAJ PI Jobs/);
assert.doesNotMatch(preferences, /Using Jobs as:/);
assert.doesNotMatch(preferences, /<small>WELCOME<\/small>/);
assert.match(preferences, /formatPreferencePi/);
assert.match(preferences, /toFixed\(5\)/);
assert.match(preferences, /Edit pay preference/);
assert.match(preferences, /Edit location preferences/);
assert.match(preferences, /Job title and work-area preferences/);
console.log("Jobs UI tests passed.");
