import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const page = readFileSync(new URL("../src/pages/jobs/JobsPage.tsx", import.meta.url), "utf8");
const api = readFileSync(new URL("../src/lib/jobsApi.ts", import.meta.url), "utf8");
const header = readFileSync(new URL("../src/pages/jobs/JobsHeader.tsx", import.meta.url), "utf8");
const preferences = readFileSync(new URL("../src/pages/jobs/JobPreferencesPanel.tsx", import.meta.url), "utf8");
const styles = readFileSync(new URL("../src/pages/jobs/JobsPage.css", import.meta.url), "utf8");

assert.match(page, /Loading live opportunities/);
assert.match(page, /loading && kind !== "home"/);
assert.match(page, /kind !== "post" \? <nav className="jobs-mobile-nav">/);
assert.match(page, /limited offline catalog/);
assert.match(page, /URLSearchParams/);
assert.match(api, /location\?: string/);

assert.match(page, /saveJobsProfileSection/);
assert.doesNotMatch(page, /id="jobs-profile-details"/);
assert.doesNotMatch(page, /localStorage\.setItem\("smaj_jobs_profile"/);
assert.match(page, /updateEmployerApplication/);
assert.match(page, /Submit company for review/);
assert.match(header, /pointerdown/);
assert.match(header, /event\.key === "Escape"/);
assert.match(header, /jobs-menu-backdrop/);
assert.match(header, /setMenuOpen\(value => !value\)/);
assert.doesNotMatch(header, /My professional profile/);
assert.doesNotMatch(header, /\["employer", "Employer dashboard"\]/);
assert.match(header, /Activity on profile/);
assert.match(header, /Employer invites/);
assert.match(header, /activity\?tab=actions/);
assert.match(header, /Job alerts/);
assert.doesNotMatch(header, /My CV and documents/);
assert.doesNotMatch(header, /Verification status/);
assert.match(header, /Settings/);
assert.match(header, /Manage jobs/);
assert.doesNotMatch(header, /\["post", "Post a job"\]/);
assert.doesNotMatch(header, /\["employer#candidates", "Candidates"\]/);
assert.doesNotMatch(header, /\["companies", "Company profile"\]/);
assert.doesNotMatch(header, /\["employer#verification", "Company verification"\]/);
assert.doesNotMatch(header, /\["", "Home"\]/);
assert.doesNotMatch(header, /\["search", "Find jobs"\]/);
assert.doesNotMatch(header, /\["saved", "Saved jobs"\]/);
assert.match(styles, /:has\(\.jobs-header > nav\.open\) \.jobs-mobile-nav/);
assert.match(page, /Search Appearances/);
assert.match(page, /Employer Actions/);
assert.match(page, /getJobsActivity/);
assert.match(header, /workspaceMode === "employer"/);
assert.match(header, /Find work/);
assert.match(header, /Hire talent/);
assert.match(page, /Hiring that's simpler, faster, and more human/);
assert.match(page, /The people you're looking for are here/);
assert.match(page, /jobs-employer-hero-video/);
assert.match(page, /jobs-employer-hero\.webm/);
assert.match(page, /navigate\("\/services\/jobs"\)/);
assert.match(page, /jobs-employer-contact-form/);
assert.match(page, /Company website \(optional\)/);
assert.match(page, /For account management communication\. Not visible to job seekers\./);
assert.match(page, /How did you hear about us\?/);
assert.match(page, /jobs-employer-title-form/);
assert.match(page, /filteredEmployerJobTitles/);
assert.match(page, /postJobTitle\.trim\(\)\.toLowerCase\(\)/);
assert.match(page, /Delivery Driver/);
assert.match(page, /setPostJobTitle\(title\)/);
assert.match(page, /Location type \*/);
assert.match(page, /Work from a set location/);
assert.match(page, /Travel to different sites/);
assert.match(page, /No on-site work required/);
assert.match(page, /Some on-site work required/);
assert.match(page, /setPostStep\("location"\)/);
assert.match(page, /setPostStep\("title"\)/);
assert.match(page, /defaultValue=\{selectedPostLocationType\.mode\}/);
assert.match(page, /Number of hires \*/);
assert.match(page, /Hiring timeframe \*/);
assert.match(page, /Job type \*/);
assert.match(page, /Salary \*/);
assert.match(page, /Benefits/);
assert.match(page, /Job description \*/);
assert.match(page, /Sponsor job/);
assert.match(page, /No thanks/);
assert.match(page, /setPostStep\("sponsor"\)/);
assert.match(page, /postSponsorPlan/);
assert.match(page, /activeWorkspaceMode === "candidate"/);
assert.match(page, /SMAJ PI HUB/);
assert.match(page, /Add another company/);
assert.match(page, /newCompanyName/);
assert.match(page, /no separate Jobs login is needed/);
assert.doesNotMatch(page, /Sign in with your Pi account/);
assert.doesNotMatch(page, /Your SMAJ PI HUB photo and identity/);
assert.match(page, /profile-country-options/);
assert.match(page, /Search for your country/);
assert.doesNotMatch(page, /Profile saved to your SMAJ account/);
assert.match(page, /jobs-quick-search/);
assert.match(page, /Country, city or remote/);
assert.match(page, /Recommended jobs/);
assert.match(page, /recommendedJobs/);
assert.match(page, /jobs-search-sheet/);
assert.match(page, /Search suggestions/);
assert.match(page, /smaj_jobs_recent_searches/);
assert.match(page, /jobSearchSuggestions/);
assert.match(page, /locationSheetOpen/);
assert.match(page, /locationSuggestions/);
assert.match(page, /Your location/);
assert.match(page, /Search city, country, or remote/);
assert.match(page, /normalizeJobLocation/);
assert.match(page, /Jobs in \$\{effectiveLocation\}/);
assert.match(page, /No jobs available in \$\{effectiveLocation\}/);
assert.match(page, /Is this your current profile photo/);
assert.match(page, /confirmJobsProfileAvatar/);
assert.match(page, /avatarConfirmationValue/);
assert.match(page, /avatarConfirmationState/);
assert.match(page, /Saving…/);
assert.match(page, /✓ Saved/);
assert.match(page, /deferAvatarConfirmation/);
assert.match(page, /returnTo=%2Fservices%2Fjobs%2Fprofile/);
assert.match(page, /profileCompletion/);
assert.match(page, /Pending Actions/);
assert.match(page, /Hi \{user\?\.displayName/);
assert.match(page, /Updated Today/);
assert.match(page, /Upload PDF CV/);
assert.match(page, /aria-label="CV options"/);
assert.match(page, /jobs-cv-document/);
assert.match(page, /CV Headline/);
assert.match(page, /Employment Details/);
assert.match(page, /jobs-profile-editor/);
assert.match(page, /saveJobsProfileSection/);
assert.doesNotMatch(page, /<strong>\{formatJobCompensation\(job\.salary\)\}<\/strong>/);
assert.match(page, /Profile Visibility/);
assert.match(page, /Basic details visible to employers/);
assert.match(page, /Connected to Pi Network/);
assert.match(page, /No additional Jobs password required/);
assert.doesNotMatch(page, /Connected to Google/);
assert.match(page, /Search verified company name/);
assert.match(page, /smaj_jobs_blocked_employers/);
assert.match(page, /salaryFromUsdt\(2200, 3000, "mo"\)/);
assert.match(styles, /--green: #6d3df5/);
assert.match(page, /Post your first job/);
assert.match(page, /jobs-search-employer-cta/);
assert.match(preferences, /How do you want to use SMAJ PI Jobs/);
assert.doesNotMatch(preferences, /Using Jobs as:/);
assert.doesNotMatch(preferences, /<small>WELCOME<\/small>/);
assert.match(preferences, /formatPreferencePi/);
assert.match(preferences, /toFixed\(5\)/);
assert.match(preferences, /Edit pay preference/);
assert.match(preferences, /Edit location preferences/);
assert.match(preferences, /Job title and work-area preferences/);
console.log("Jobs UI tests passed.");
