import { colors, radii, spacing } from "@smaj/design-tokens";
import { router, useLocalSearchParams } from "expo-router";
import * as Linking from "expo-linking";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { StatusPill } from "@/components/status-pill";
import { config } from "@/constants/config";
import { services } from "@/lib/services";
export default function ServiceDetail(){const {slug}=useLocalSearchParams<{slug:string}>();const service=services.find(item=>item.slug===slug);if(!service)return <SafeAreaView style={styles.safe}><Text>Service not found.</Text></SafeAreaView>;const webSlug=service.slug==="food"?"food-delivery":service.slug;return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={()=>router.back()}><Text style={styles.back}>&lt; Back</Text></Pressable><Text style={styles.headerTitle}>SMAJ PI HUB</Text></View><View style={styles.body}><Text style={styles.icon}>{service.icon}</Text><StatusPill status={service.status}/><Text style={styles.title}>{service.name}</Text><Text style={styles.description}>{service.description}</Text><View style={styles.shared}><Text style={styles.sharedTitle}>Shared platform data</Text><Text style={styles.description}>This native screen will use the same users, content and API as the existing Web and Pi Browser service.</Text></View><Pressable style={styles.button} onPress={()=>void Linking.openURL(`${config.webBaseUrl}/services/${webSlug}`)}><Text style={styles.buttonText}>Open current service experience</Text></Pressable></View></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},header:{height:64,paddingHorizontal:spacing.lg,flexDirection:"row",alignItems:"center",gap:spacing.lg,backgroundColor:colors.surface,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.border},back:{color:colors.primary,fontWeight:"800"},headerTitle:{color:colors.text,fontWeight:"900"},body:{padding:spacing.xl,alignItems:"center",gap:spacing.lg},icon:{fontSize:82},title:{color:colors.text,fontSize:30,fontWeight:"900",textAlign:"center"},description:{color:colors.textMuted,fontSize:15,lineHeight:23,textAlign:"center"},shared:{padding:spacing.lg,gap:spacing.sm,borderRadius:radii.md,backgroundColor:colors.surfaceMuted},sharedTitle:{color:colors.primaryDark,fontWeight:"900",fontSize:16,textAlign:"center"},button:{paddingHorizontal:20,paddingVertical:14,borderRadius:radii.pill,backgroundColor:colors.primary},buttonText:{color:"#FFF",fontWeight:"900"}});