import { useCallback, useEffect, useMemo, useState } from "react";
import { axiosClient } from "../../lib/axiosClient";
import type { TeacherApplication } from "../../lib/educationApi";

type ReviewStatus = "under_review" | "changes_required" | "approved" | "rejected";
const AdminTeacherApplicationsPage = () => {
  const [items, setItems] = useState<TeacherApplication[]>([]);
  const [filter, setFilter] = useState("submitted");
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState("");
  const [message, setMessage] = useState("");
  const load = useCallback(async () => setItems((await axiosClient.get<{ applications: TeacherApplication[] }>("/education/admin/teacher-applications")).data.applications || []), []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => filter === "all" ? items : items.filter(item => item.status === filter), [filter, items]);
  const review = async (id: string, status: ReviewStatus) => { setBusy(id); try { await axiosClient.patch(`/education/admin/teacher-applications/${id}`, { status, reviewer_notes: notes[id] || "" }); setMessage(`Application ${status.replace(/_/g, " ")}.`); await load(); } finally { setBusy(""); } };
  return <main className="private-page"><section className="private-page-heading"><span>EDUCATION REVIEW</span><h1>Teacher Applications</h1><p>Review identity, qualifications, course plans, evidence, and teaching quality before granting instructor access.</p></section>{message && <div className="private-alert success">{message}</div>}<section className="admin-filter-bar"><label>Status filter<select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All</option><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="under_review">Under review</option><option value="changes_required">Changes required</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label><span>{visible.length} applications</span></section><div className="management-list">{visible.map(item => <article className="report-card onboarding-admin-card" key={item.id}><div><span>{item.applicant_role.replace(/_/g, " ")} · {item.status.replace(/_/g, " ")}</span><h3>{item.full_name}</h3><p>{item.email} · {item.country} · @{item.pi_username}</p><p><strong>{item.headline}</strong><br />{item.biography}</p><p><strong>Subjects:</strong> {item.subjects.join(" · ")} · {item.experience_years} years · {item.languages.join(", ")}</p><p><strong>Course:</strong> {item.proposed_course_title} · {item.proposed_category} · {item.proposed_level} · {item.proposed_price_pi} Pi</p><p><strong>Education:</strong> {item.education || "Not supplied"}<br /><strong>Certifications:</strong> {item.certifications || "Not supplied"}</p><p><strong>Evidence:</strong> {item.evidence_documents?.length ? item.evidence_documents.map(doc => <a key={doc.url} href={doc.url} target="_blank" rel="noreferrer"> {doc.name}</a>) : " None"}{item.sample_lesson_url && <a href={item.sample_lesson_url} target="_blank" rel="noreferrer"> · Sample lesson</a>}</p><label>Private review notes<textarea rows={3} value={notes[item.id] ?? item.reviewer_notes ?? ""} onChange={e => setNotes(current => ({ ...current, [item.id]: e.target.value }))} /></label></div><strong className={item.status === "approved" ? "resolved" : "open"}>{item.status.replace(/_/g, " ")}</strong><div className="row-actions"><button disabled={busy === item.id} onClick={() => void review(item.id, "under_review")}>Reviewing</button><button disabled={busy === item.id} onClick={() => void review(item.id, "changes_required")}>Request changes</button><button disabled={busy === item.id} onClick={() => void review(item.id, "approved")}>Approve</button><button className="danger" disabled={busy === item.id} onClick={() => void review(item.id, "rejected")}>Reject</button></div></article>)}</div>{!visible.length && <div className="private-state"><h2>No teacher applications</h2><p>There are no applications matching this filter.</p></div>}</main>;
};
export default AdminTeacherApplicationsPage;