import { useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import { Link } from "react-router-dom";
import SchoolOutlinedIcon from "@mui/icons-material/SchoolOutlined";
import UploadFileOutlinedIcon from "@mui/icons-material/UploadFileOutlined";
import VerifiedOutlinedIcon from "@mui/icons-material/VerifiedOutlined";
import AppLayout from "../../layouts/AppLayout";
import EducationHeader from "./EducationHeader";
import { useAuthContext } from "../../contexts/AuthContext";
import { getMyTeacherApplication, saveTeacherApplication, uploadTeacherEvidence, type TeacherApplication } from "../../lib/educationApi";
import "./TeachOnSmajPage.css";

const split = (value: string) => value.split(",").map(item => item.trim()).filter(Boolean);
const initial = { applicant_role: "tutor", full_name: "", email: "", phone: "", country: "", avatar_url: "", headline: "", biography: "", subjects: "", experience_years: "0", languages: "", education: "", certifications: "", proposed_course_title: "", proposed_category: "Technology", proposed_level: "Beginner", delivery_method: "Self-paced course", proposed_price_pi: "0", sample_lesson_url: "", pi_username: "", identity_confirmed: false, quality_agreed: false, terms_agreed: false };

const TeachOnSmajPage = () => {
  const { user } = useAuthContext();
  const [form, setForm] = useState(initial);
  const [application, setApplication] = useState<TeacherApplication | null>(null);
  const [documents, setDocuments] = useState<Array<{ name: string; url: string }>>([]);
  const [review, setReview] = useState(false);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const set = (key: string, value: string | boolean) => setForm(current => ({ ...current, [key]: value }));

  useEffect(() => { void getMyTeacherApplication().then(saved => {
    setApplication(saved);
    if (saved) {
      setDocuments(saved.evidence_documents || []);
      setForm({ ...initial, ...saved, subjects: saved.subjects.join(", "), languages: saved.languages.join(", "), experience_years: String(saved.experience_years), proposed_price_pi: String(saved.proposed_price_pi) });
    } else setForm(current => ({ ...current, full_name: user?.displayName || user?.piUsername || user?.username || "", country: user?.country || "", avatar_url: user?.avatar || "", phone: user?.contactPhone || "", pi_username: user?.piUsername || user?.username || "" }));
  }).catch(() => setMessage("Could not load your application.")); }, [user]);

  const payload = () => ({ ...form, experience_years: Number(form.experience_years), proposed_price_pi: Number(form.proposed_price_pi), subjects: split(form.subjects), languages: split(form.languages), evidence_documents: documents });
  const save = async (action: "draft" | "submit") => { setBusy(true); setMessage(""); try { const saved = await saveTeacherApplication({ ...payload(), action }); setApplication(saved); setReview(false); setMessage(action === "submit" ? "Application submitted. SMAJ Education will review your evidence." : "Draft saved."); } catch (error: any) { setMessage(error?.response?.data?.error || "Application could not be saved."); } finally { setBusy(false); } };
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); try { const uploaded = await uploadTeacherEvidence(file); setDocuments(items => [...items, uploaded].slice(0, 8)); setMessage("Evidence uploaded securely. Save your draft to keep it."); } catch (error: any) { setMessage(error.message || "Evidence upload failed."); } finally { setBusy(false); event.target.value = ""; } };
  const locked = application?.status === "approved" || application?.status === "under_review" || application?.status === "submitted";

  return <AppLayout showHeader={false} showFooter={false}><main className="teach-page"><EducationHeader query="" onQueryChange={() => undefined} searchPath="/services/education/courses" />
    <section className="teach-hero"><span>TEACH ON SMAJ</span><h1>Share your expertise. Teach worldwide. Earn Pi.</h1><p>Apply as an individual tutor or education provider. Every public instructor is reviewed before publishing courses or accepting learners.</p><div><VerifiedOutlinedIcon /> Identity reviewed <VerifiedOutlinedIcon /> Qualifications checked <VerifiedOutlinedIcon /> Quality-first courses</div></section>
    {application && <section className={`teach-status ${application.status}`}><b>Application status: {application.status.replace(/_/g, " ")}</b><p>{application.reviewer_notes || (application.status === "approved" ? "You are approved to create courses and manage learners." : "We will notify you when the review status changes.")}</p>{application.status === "approved" && <Link to="/app/services/education/courses">Open Instructor Dashboard</Link>}</section>}
    {review ? <section className="teach-review"><header><SchoolOutlinedIcon /><div><span>FINAL REVIEW</span><h2>Confirm your teaching application</h2></div></header><dl><div><dt>Applicant</dt><dd>{form.full_name} · {form.applicant_role.replace(/_/g, " ")}</dd></div><div><dt>Teaching</dt><dd>{form.headline}<br />{form.subjects}</dd></div><div><dt>Proposed course</dt><dd>{form.proposed_course_title} · {form.proposed_category} · {form.proposed_level}</dd></div><div><dt>Price and delivery</dt><dd>{form.proposed_price_pi} Pi · {form.delivery_method}</dd></div><div><dt>Evidence</dt><dd>{documents.length} document(s) · {form.sample_lesson_url || "No sample link"}</dd></div></dl><div className="teach-actions"><button type="button" className="secondary" onClick={() => setReview(false)}>Edit application</button><button type="button" disabled={busy} onClick={() => void save("submit")}>Submit for review</button></div></section> :
    <form className="teach-form" onSubmit={(e: FormEvent) => { e.preventDefault(); setReview(true); }}>
      <fieldset disabled={locked || busy}><legend>1. Choose how you will teach</legend><div className="teach-role"><label className={form.applicant_role === "tutor" ? "selected" : ""}><input type="radio" checked={form.applicant_role === "tutor"} onChange={() => set("applicant_role", "tutor")} />Individual Tutor<small>Lessons, coaching, or your own courses</small></label><label className={form.applicant_role === "education_provider" ? "selected" : ""}><input type="radio" checked={form.applicant_role === "education_provider"} onChange={() => set("applicant_role", "education_provider")} />Education Provider<small>Academy, school, or training organization</small></label></div></fieldset>
      <fieldset disabled={locked || busy}><legend>2. Confirm your SMAJ profile</legend><div className="teach-profile-preview">{form.avatar_url ? <img src={form.avatar_url} alt="" /> : <span>{form.full_name.slice(0, 1) || "T"}</span>}<div><b>{form.full_name || "Your full name"}</b><small>@{form.pi_username || "Pi username"}</small></div></div><div className="teach-grid"><label>Full legal name *<input value={form.full_name} onChange={e => set("full_name", e.target.value)} required /></label><label>Email *<input type="email" value={form.email} onChange={e => set("email", e.target.value)} required /></label><label>Phone<input value={form.phone} onChange={e => set("phone", e.target.value)} /></label><label>Country *<input value={form.country} onChange={e => set("country", e.target.value)} required /></label></div></fieldset>
      <fieldset disabled={locked || busy}><legend>3. Teaching profile</legend><label>Professional headline *<input value={form.headline} onChange={e => set("headline", e.target.value)} placeholder="Example: Mathematics tutor for secondary students" required /></label><label>Biography *<textarea value={form.biography} onChange={e => set("biography", e.target.value)} rows={5} required /></label><div className="teach-grid"><label>Subjects (comma separated) *<input value={form.subjects} onChange={e => set("subjects", e.target.value)} required /></label><label>Languages (comma separated) *<input value={form.languages} onChange={e => set("languages", e.target.value)} required /></label><label>Years of experience<input type="number" min="0" max="80" value={form.experience_years} onChange={e => set("experience_years", e.target.value)} /></label></div><label>Education<textarea value={form.education} onChange={e => set("education", e.target.value)} rows={3} /></label><label>Certifications<textarea value={form.certifications} onChange={e => set("certifications", e.target.value)} rows={3} /></label></fieldset>
      <fieldset disabled={locked || busy}><legend>4. Your first course plan</legend><label>Proposed course title *<input value={form.proposed_course_title} onChange={e => set("proposed_course_title", e.target.value)} required /></label><div className="teach-grid"><label>Category<select value={form.proposed_category} onChange={e => set("proposed_category", e.target.value)}><option>Technology</option><option>Business</option><option>Exam Prep</option><option>Languages</option><option>Personal Development</option></select></label><label>Level<select value={form.proposed_level} onChange={e => set("proposed_level", e.target.value)}><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>All levels</option></select></label><label>Delivery<select value={form.delivery_method} onChange={e => set("delivery_method", e.target.value)}><option>Self-paced course</option><option>Live online tutoring</option><option>Hybrid</option></select></label><label>Proposed price in Pi<input type="number" min="0" step="0.01" value={form.proposed_price_pi} onChange={e => set("proposed_price_pi", e.target.value)} /></label></div></fieldset>
      <fieldset disabled={locked || busy}><legend>5. Evidence and sample lesson</legend><label className="teach-upload"><UploadFileOutlinedIcon /><b>Upload qualification or ID PDF</b><small>Private review only · PDF · up to the platform upload limit</small><input type="file" accept="application/pdf" onChange={upload} /></label>{documents.map((doc, i) => <div className="teach-document" key={doc.url}><a href={doc.url} target="_blank" rel="noreferrer">{doc.name}</a><button type="button" onClick={() => setDocuments(items => items.filter((_, n) => n !== i))}>Remove</button></div>)}<label>Sample lesson or portfolio URL<input type="url" value={form.sample_lesson_url} onChange={e => set("sample_lesson_url", e.target.value)} placeholder="https://" /></label></fieldset>
      <fieldset disabled={locked || busy}><legend>6. Confirm and agree</legend><label className="teach-check"><input type="checkbox" checked={form.identity_confirmed} onChange={e => set("identity_confirmed", e.target.checked)} required />The name, profile photo, identity and qualifications are mine and accurate.</label><label className="teach-check"><input type="checkbox" checked={form.quality_agreed} onChange={e => set("quality_agreed", e.target.checked)} required />I agree to SMAJ teaching and content-quality standards.</label><label className="teach-check"><input type="checkbox" checked={form.terms_agreed} onChange={e => set("terms_agreed", e.target.checked)} required />I accept the platform terms and understand approval can be withdrawn for violations.</label></fieldset>
      {message && <p className="teach-message" role="status">{message}</p>}<div className="teach-actions"><button type="button" className="secondary" disabled={locked || busy} onClick={() => void save("draft")}>Save draft</button><button type="submit" disabled={locked || busy}>Review application</button></div>
    </form>}
  </main></AppLayout>;
};
export default TeachOnSmajPage;